development:
  bucket: afrojamsnite_bucket
  access_key_id: 
  secret_access_key: 

test:
  bucket: afrojamsnite_test_bucket
  access_key_id: 
  secret_access_key: 

production:
  bucket: afrojamsnite_bucket
  access_key_id: 
  secret_access_key: 


